#ifndef FACE_WATCHLIST_HPP
#define FACE_WATCHLIST_HPP

#include <opencv2/opencv.hpp>
#include <opencv2/dnn.hpp>
#include <string>
#include <vector>
#include <err_log/Logger.hpp>
#include "interface/BaseMicroservice.hpp"  // ensure inheritance is visible here

/**
 * @brief Represents a known face entry in the watchlist.
 * 
 * Each entry contains:
 * - A unique ID
 * - A human-readable name (e.g., filename or person’s name)
 * - A feature embedding vector generated by the face recognition model
 */
struct KnownFace {
    int id;                /**< Unique identifier for the face */
    std::string name;      /**< Human-readable label (e.g., filename or person’s name) */
    cv::Mat embedding;     /**< Feature vector representing the face */
};

/**
 * @brief Microservice for managing a watchlist of known faces.
 * 
 * FaceWatchlist provides functionality to:
 * - Load and store known faces with embeddings
 * - Compute embeddings for new faces using a DNN model
 * - Compare new faces against the watchlist using cosine similarity
 * - Configure thresholds and cascade paths
 * - Monitor live camera feed for restricted area detection
 * 
 * Inherits from BaseMicroservice to integrate with Smart_Store’s
 * distributed architecture (networking, messaging, serialization).
 */
class FaceWatchlist : public BaseMicroservice {
public:
    /** @brief Default constructor initializes threshold and cascade path. */
    FaceWatchlist();

    /** @brief Virtual destructor for polymorphic base. */
    ~FaceWatchlist() override = default;

    // ---------------- Threshold Controls ----------------

    /** @brief Get the current similarity threshold used for recognition. */
    double getThreshold() const;

    /** @brief Set a new similarity threshold. */
    void setThreshold(double newThreshold);

    /** @brief Reset similarity threshold to the default value (0.65). */
    void resetThreshold();

    // ---------------- Cascade Path Controls ----------------

    /** @brief Set a custom Haar cascade path for face detection. */
    void setCascadePath(const std::string& path);

    /** @brief Get the currently configured cascade path. */
    std::string getCascadePath() const;

    // ---------------- Watchlist Operations ----------------

    /**
     * @brief Load known faces from image file paths.
     * 
     * Each image is converted into an embedding and stored in the watchlist.
     * @param filePaths Vector of image file paths.
     */
    void loadKnownFaces(const std::vector<std::string>& filePaths);

    /**
     * @brief Check if a given face ROI matches any known face in the watchlist.
     * 
     * @param faceROI Cropped face image (region of interest).
     * @return True if a match is found, false otherwise.
     */
    bool checkForKnownFace(const cv::Mat& faceROI);

    // ---------------- Watchlist Management ----------------

    /** @brief Get the number of known faces currently stored in the watchlist. */
    size_t getKnownFaceCount() const;

    /** @brief Reset (clear) all known faces from the watchlist. */
    void resetKnownFaces();

    /**
     * @brief Monitor live camera feed for restricted area detection.
     * 
     * Uses either a custom cascade path or defaults to system cascade.
     * @param cascadePath Optional path to cascade XML file. If empty, defaults are used.
     */
    void monitorCamera(const std::string& cascadePath = "");

private:
    // ---------------- Internal Helpers ----------------

    /**
     * @brief Compute an embedding vector for a given face ROI.
     * 
     * @param faceROI Cropped face image.
     * @return Embedding vector as cv::Mat.
     */
    cv::Mat computeEmbedding(const cv::Mat& faceROI);

    /**
     * @brief Compute cosine similarity between two embeddings.
     * 
     * @param a First embedding vector.
     * @param b Second embedding vector.
     * @return Similarity score in range [-1, 1].
     */
    double cosineSimilarity(const cv::Mat& a, const cv::Mat& b);

    // ---------------- Members ----------------

    double similarityThreshold_;                  /**< Current similarity threshold */
    static constexpr double DEFAULT_THRESHOLD = 0.65; /**< Default threshold value */

    std::vector<KnownFace> knownFaces_;           /**< Storage for known faces */
    cv::CascadeClassifier faceCascade_;           /**< Haar cascade for face detection */
    std::string cascadePath_;                     /**< Path to cascade file */
};

#endif // FACE_WATCHLIST_HPP
